/**
 * Downloads the webfonts the site uses from Google Fonts into `public/fonts`
 * and writes `src/fonts.css` with matching @font-face rules.
 *
 * Self-hosting is what lets the first paint start without a round trip to
 * fonts.googleapis.com followed by a second one to fonts.gstatic.com — that
 * chain was the longest one on the critical path.
 *
 * Google serves variable files for most of these families, so the same URL
 * comes back for every requested weight. Faces that share a URL are collapsed
 * into one file and one rule with a weight *range*, otherwise the browser
 * would download the same bytes once per weight.
 *
 * Run: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500&family=IBM+Plex+Sans+Arabic:wght@300;400;500;600&family=Inter+Tight:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600&display=swap'

/** Subsets the site actually renders. Everything else is dead weight. */
const KEEP = new Set(['latin', 'latin-ext', 'arabic'])

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const outDir = path.resolve('public/fonts')
await mkdir(outDir, { recursive: true })

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Google emits `/* subset */` immediately before each @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)]
if (!blocks.length) throw new Error('No @font-face blocks parsed from Google Fonts CSS')

/** key: family|subset|style|url -> face */
const faces = new Map()

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1])
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal'
  const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1]
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]
  if (!family || !weight || !url) continue

  const key = `${family}|${subset}|${style}|${url}`
  const face = faces.get(key)
  if (face) {
    face.min = Math.min(face.min, weight)
    face.max = Math.max(face.max, weight)
  } else {
    faces.set(key, { family, subset, style, url, range, min: weight, max: weight })
  }
}

const rules = []

for (const face of faces.values()) {
  const slug = face.family.toLowerCase().replace(/\s+/g, '-')
  // A collapsed variable face is named for its range, a single weight for itself.
  const weightPart = face.min === face.max ? `${face.min}` : `${face.min}-${face.max}`
  const file = `${slug}-${face.subset}-${weightPart}.woff2`

  const res = await fetch(face.url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${res.status} for ${face.url}`)
  await writeFile(path.join(outDir, file), Buffer.from(await res.arrayBuffer()))

  rules.push(
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.min === face.max ? face.min : `${face.min} ${face.max}`};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      face.range ? `  unicode-range: ${face.range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  )
}

await writeFile(
  path.resolve('src/fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${rules.join('\n\n')}\n`,
)

console.log(`${rules.length} font files -> public/fonts, ${rules.length} rules -> src/fonts.css`)
