// Generated by scripts/prep-case-art.mjs — do not edit by hand.
// Pixel sizes and inline blurred previews for every shipped case photograph.

export const CASE_ART = {
  "full-arch-both": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoYABAAPu1kq04ppaQiMAgBMB2JZACdL1ABkcihVUYLFQYnPQAA/uUAJesr8b1uOqlTQvMtk1qYpcAdZkbDzRIqvXO1X9h3ZYxaXpxykRfUOghp90J59byU4xQAAA=="
  },
  "upper-arch-fixed": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoYABAAPu1iqk2ppaQiMAgBMB2JaACdMoRwACx5D36FBwI+5OjIAP7mAzGkv+dpY3E8CIlDQrL1DioeaTRrVDnV75f7idPlJ4A9nSJAEgsERtjZs+HzPqEyGr8o+fzLc8Uz/QAA"
  },
  "smile-portrait": {
    "width": 854,
    "height": 1280,
    "lg": {
      "width": 854,
      "height": 1280
    },
    "sm": {
      "width": 640,
      "height": 959
    },
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBgCdASoYACQAPu1ysFKppqSipWmZMB2JYgC2yAlVTmaf/VKXgEjqjd15lzNH+YZypPX9BVTMFuAAAP7R3dz1ESSx486jQKUXmJZMpCl0MmE96r778H8Ke8tzcXz92XQeh2FgH1m4oM6y6lsI9ZHLYYCdKIbMinDGTZM0b9X3e3gQQpKVYQR7wa3f5TM7zwfkGojby6wgelNUVo2+u/4jzmNAAAAA"
  },
  "upper-arch-closeup": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoYABAAPu1iqk2ppaQiMAgBMB2JQBYdhC4c55QVAomHcjrcAP7vX+IrHRzfJrCMQZ7MeDbpeNBFgAg4kwNFesOCcdr1PdVL8pEw2AAA"
  },
  "full-mouth-smile": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoYABAAPu1qrU8ppiQiMAgBMB2JQBOgA8M/OrT1fwkzzEatFQAA/u6hVimw4Xcep+uddgPy79vfGTZtG1JVUV3YEOqSH30wlDGOI0Vs4fbAfCsnDUAAAA=="
  },
  "anterior-crowns-retractor": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZgCdMoRwAB6E7HdTcVpTNAAA/tzvb9FjI35UpUOPp7W9Hk8qD1nL+smuJ8NVY0eeclc6RdKq7OvQ1N9zLfVS2Vou/xIaLdrlKosAAAA="
  },
  "anterior-crowns-smile": {
    "width": 1280,
    "height": 854,
    "lg": {
      "width": 1280,
      "height": 854
    },
    "sm": {
      "width": 640,
      "height": 427
    },
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoYABAAPu1kqU4ppaOiMAgBMB2JQBOmUABN4rHUMgtFHyhVWNAA/W3IwtZHkzoygL1afbuA7Wu+NFc4pn4OfqLhQBMesY+V1Qgpi74gAAA="
  },
  "lab-master-cast": {
    "width": 854,
    "height": 1280,
    "lg": {
      "width": 854,
      "height": 1280
    },
    "sm": {
      "width": 640,
      "height": 959
    },
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBQCdASoYACQAPt1iok2opiMmNVgMARAbiUAXYAIC3ApqrM62k4rJBR4euXtPuhdMrmdxkAD8UpPKkQowo0zFT22yOjg5N3Krhuq3QOjHc4BR4MPWqt2IFui/a02VsniqocnctX4AAA=="
  },
  "veneers-after": {
    "width": 1080,
    "height": 675,
    "lg": {
      "width": 1080,
      "height": 675
    },
    "sm": {
      "width": 640,
      "height": 400
    },
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQBACdASoYAA8APu1iqU2ppaOiMAgBMB2JQBWAA3OnLF94tI97sKVZgADMO91HLE+QTHorXnY6nIUdSYc+qoXUtsNtLcVIAAA="
  },
  "veneers-before": {
    "width": 1080,
    "height": 675,
    "lg": {
      "width": 1080,
      "height": 675
    },
    "sm": {
      "width": 640,
      "height": 400
    },
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JQBUeg+pkMZV9Oot3AAD+MNC1a5s3wdJgbkYRho1lXpsC4plEQN4h0T03pOF0x1wAAA=="
  }
} as const
