/**
 * Inspects the PDFs the build just wrote and reports what is actually in them.
 *
 * This exists because "the build succeeded" says nothing about whether a press
 * can use the result. Every line below is read back out of the file: the page
 * count, the sheet and trim sizes in millimetres, how the glyphs are carried,
 * and whether any raster crept into artwork that is supposed to be vector.
 *
 * The font line is the interesting one. Headless Chrome on this platform carries
 * web-font glyphs as **Type 3** fonts — each glyph an embedded vector procedure
 * — rather than embedding the TrueType file. Type 3 is valid, fully vector, and
 * resolution-independent, so it prints correctly; what it costs is text search
 * and copy inside the PDF, and it can trip a strict preflight profile. Chrome
 * embeds a real TrueType font only for faces installed on the operating system,
 * so the remedy, if a printer refuses Type 3, is to install Cinzel, Inter, Inter
 * Tight and IBM Plex Sans Arabic (all free, all on Google Fonts) and run the
 * build again — no layout changes needed.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { PDFDict, PDFDocument, PDFName, PDFStream } from 'pdf-lib'

const pt2mm = (pt) => +((pt * 25.4) / 72).toFixed(2)

/** Walks every indirect object, since Chrome writes them into object streams. */
function surveyObjects(doc) {
  const survey = { type3: 0, trueType: 0, embeddedFiles: 0, images: 0, faces: new Set() }
  for (const [, obj] of doc.context.enumerateIndirectObjects()) {
    if (!(obj instanceof PDFDict) && !(obj instanceof PDFStream)) continue
    const dict = obj instanceof PDFStream ? obj.dict : obj
    const subtype = String(dict.get(PDFName.of('Subtype')) ?? '')
    if (subtype === '/Type3') survey.type3++
    if (subtype === '/TrueType' || subtype === '/Type0') survey.trueType++
    if (subtype === '/Image') survey.images++
    if (dict.get(PDFName.of('FontFile2')) || dict.get(PDFName.of('FontFile3'))) survey.embeddedFiles++
    const base = dict.get(PDFName.of('BaseFont'))
    if (base) survey.faces.add(String(base).replace(/^\/[A-Z]{6}\+/, '/'))
  }
  return survey
}

function describe(name, doc) {
  const survey = surveyObjects(doc)
  const pages = doc.getPages().map((page) => {
    const media = page.getSize()
    const trim = page.node.TrimBox?.()?.asRectangle?.()
    return {
      sheet: `${pt2mm(media.width)} × ${pt2mm(media.height)} mm`,
      trim: trim ? `${pt2mm(trim.width)} × ${pt2mm(trim.height)} mm` : 'not set',
    }
  })

  const glyphs =
    survey.type3 && survey.trueType
      ? `mixed — ${survey.trueType} embedded TrueType, ${survey.type3} Type 3 (vector outlines)`
      : survey.type3
        ? `Type 3 (vector outlines, ${survey.type3} faces) — prints correctly, not searchable`
        : survey.trueType
          ? `embedded TrueType (${survey.trueType} faces, ${survey.embeddedFiles} font files)`
          : 'no text'

  return { name, pages, glyphs, images: survey.images }
}

/** Reads back every PDF in `dir` and writes a plain-text preflight report. */
export async function preflight(dir, { stamp }) {
  const files = (await readdir(dir)).filter((f) => f.endsWith('.pdf')).sort()
  const reports = []

  for (const file of files) {
    const doc = await PDFDocument.load(await readFile(`${dir}/${file}`))
    reports.push(describe(file, doc))
  }

  const lines = [
    'OZEA DENTAL CLINIC — PRINT PREFLIGHT',
    `Read back from the files in ${dir}/ on ${stamp}.`,
    'Generated by scripts/brand-kit/preflight.mjs — do not edit by hand.',
    '',
    'Colour space:  RGB. Convert to the house CMYK profile at output.',
    'Cut to:        the TrimBox, not the page edge.',
    '',
  ]

  for (const report of reports) {
    lines.push(report.name)
    const unique = new Map()
    for (const page of report.pages) {
      const key = `${page.sheet} | ${page.trim}`
      unique.set(key, (unique.get(key) ?? 0) + 1)
    }
    for (const [key, count] of unique) {
      const [sheet, trim] = key.split(' | ')
      lines.push(`  ${count} page(s)   sheet ${sheet}   trim ${trim}`)
    }
    lines.push(`  glyphs: ${report.glyphs}`)
    lines.push(`  raster images: ${report.images}`)
    lines.push('')
  }

  lines.push(
    'On Type 3 fonts: every glyph is an embedded vector procedure, so the type is',
    'resolution-independent and needs no font installed anywhere. It is text you',
    'cannot select or search inside the PDF. Headless Chrome only embeds a real',
    'TrueType font for faces installed on the operating system — so if a printer',
    'refuses Type 3, install Cinzel, Inter, Inter Tight and IBM Plex Sans Arabic',
    '(all free on Google Fonts) and re-run the build. Nothing in the layout moves.',
    '',
  )

  const text = lines.join('\n')
  await writeFile(`${dir}/PREFLIGHT.txt`, text)
  return { reports, text }
}
